# configure in this file all exchanges
exchanges_settings:
  bitmex:
    test: true
    ping_sec: 20
    timeout_sec: 30
    retry_sec: 5
    buffer_size: 100
    currency: XBTUSD

  binance:
    test: true
    ping_sec: 20
    timeout_sec: 30
    retry_sec: 5
    buffer_size: 100

admin:
  username: admin
  secret_token: token

db:
  host: localhost
  port: 5432
  name: tccbot_db
  user: postgres
  password: 123456
  sslmode: disable

exchanges_access:
  bitmex:
    key: key
    secret: secret

strategies:
  enable_bb: true # bolinger band
  bin_sizes: ["5m","1h"]
  retry_process_count: 5
  bb_last_candles_count: 4
  get_candles_count: 30
  rsi_count: 14
  macd_fast_count: 12
  macd_slow_count: 26
  macd_sig_count: 9
