# configure in this file all exchanges
exchanges_settings:
  bitmex:
    test: true
    ping_sec: 20
    timeout_sec: 30
    retry_sec: 5
    buffer_size: 100
    order_type: Limit # Market, Limit, Stop, StopLimit, StopMarket
    currency: XBt
    symbol: XBTUSD
    max_amount: 120 # max qty for creating order // DEPRECATED
    close_position_min_btc: 0.0004 # if unrealized pnl great than this value, place order by position
    limit_contracts_cnt: 350 # if position active contracts greater than, not place new orders
    sell_order_coef: 0.1 # coefficient * available balance = number of contracts for placing a sell order
    buy_order_coef: 0.2 # coefficient * available balance = number of contracts for placing a buy order

  binance:
    test: true
    ping_sec: 20
    timeout_sec: 30
    retry_sec: 5
    buffer_size: 100

admin:
  username: admin
  secret_token: token

exchanges_access:
  bitmex:
    key: key
    secret: secret
    testnet:
      key: key
      secret: secret

strategies_g:
  1m:
    enable_bb: false # enable bolinger band strategy
    enable_macd: false # enable macd strategy
    enable_rsi: false # enable rsi strategy
    bin_sizes: ["5m","1h"] # 5m,1h,1d
    retry_process_count: 5
    bb_last_candles_count: 4
    get_candles_count: 30
    candles_filter_enable: true
    trend_filter_enable: false
    max_filter_trend_count: 5
    max_candles_filter_count: 4
    rsi_count: 14
    rsi_min_border: 30
    rsi_max_border: 70
    rsi_trade_coef: 0.0004
    macd_fast_count: 12
    macd_slow_count: 26
    macd_sig_count: 9
  5m:
    enable_bb: false # enable bolinger band strategy
    enable_macd: false # enable macd strategy
    enable_rsi: false # enable rsi strategy
    enable_rsi_bb: true
    bin_sizes: ["5m","1h"] # 5m,1h,1d
    retry_process_count: 5
    bb_last_candles_count: 4
    get_candles_count: 30
    candles_filter_enable: true
    trend_filter_enable: false
    max_filter_trend_count: 6
    max_candles_filter_count: 4
    rsi_count: 14
    rsi_min_border: 30
    rsi_max_border: 70
    rsi_trade_coef: 0.0004
    macd_fast_count: 12
    macd_slow_count: 26
    macd_sig_count: 9
  1h:
    enable_bb: false # enable bolinger band strategy
    enable_macd: false # enable macd strategy
    enable_rsi: false # enable rsi strategy
    bin_sizes: ["5m","1h"] # 5m,1h,1d
    retry_process_count: 5
    bb_last_candles_count: 4
    get_candles_count: 30
    candles_filter_enable: true
    trend_filter_enable: false
    max_filter_trend_count: 5
    max_candles_filter_count: 4
    rsi_count: 14
    rsi_min_border: 30
    rsi_max_border: 70
    rsi_trade_coef: 0.0004
    macd_fast_count: 12
    macd_slow_count: 26
    macd_sig_count: 9

scheduler:
  position:
    enable: true
    trailing_price: 5
    profit_pnl_diff: 0.0002
    loss_pnl_diff: 0.0001

ord_proc_period_sec: 180
db_path: sqlite3://tccbot_db?x-migrations-table=schema_migrations
