name: deploy
on: [push]
jobs:

  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: scp all files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWD }}
          port: 22
          source: "."
          target: "/home/tccbot/tccbot-backend"

      - name: run tccbot-backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWD }}
          port: 22
          debug: true
          script_stop: true
          script: |
            ls -lah /usr/local/go/bin
            cd /home/tccbot/tccbot-backend && make build-usr
            ./bin/tccbot-backend -level 5 -test -logdir logs &
